version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./:/usr/share/nginx/html/project
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

  php:
    image: php:7-fpm
    volumes:
        - ./:/usr/share/nginx/html/project

  mysql:
    image: mysql:latest
    container_name: mysql 
    ports:
        - 3306:3306
    environment:
      - MYSQL_DATABASE=qqq
      - MYSQL_ROOT_PASSWORD=qqq
      - MYSQL_USER=qqq
      - MYSQL_PASSWORD=qqq
  node:
    # image: "node:8"
    # user: "node"
    # working_dir: /var/www/project
    # environment:
    #   - NODE_ENV=development
    # volumes:
    #   - ./:/var/www/project
    # expose:
    #   - "8081"
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - ./:/usr/share/nginx/html/project
    # command: "npm start"